openapi: 3.0.1
info:
  title: Map Visualizer | This API server shows the information of a bike-sharing
    system and his stations.
  version: 1.1.0
servers:
- url: /
tags:
- name: RawData
  description: Operations related with the manipulation of raw stations and system
    data.
paths:
  /api/v1/system_information:
    get:
      tags:
      - RawData
      summary: Get system information
      description: Retrieve all the system information from the GBFS
      operationId: get_system_information
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/system_information'
        "400":
          description: The Wahington DC GBFS was not found
          content:
            text/html:
              schema:
                $ref: '#/components/schemas/errorMessage'
              example: Wahington DC GBFS not found
      x-openapi-router-controller: swagger_server.controllers.raw_data_controller
  /api/v1/station_information/{station_id}:
    get:
      tags:
      - RawData
      summary: Get station information
      description: Retrieve all the information of a specific station
      operationId: get_station_information
      parameters:
      - name: station_id
        in: path
        description: ID of the station
        required: true
        style: simple
        explode: false
        schema:
          $ref: '#/components/schemas/station_id'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/station_information'
        "400":
          description: The provided station was not found
          content:
            text/html:
              schema:
                $ref: '#/components/schemas/errorMessage'
              example: Inexistent station Id
      x-openapi-router-controller: swagger_server.controllers.raw_data_controller
  /api/v1/stations:
    get:
      tags:
      - RawData
      summary: Get list of stations
      description: Retrieve all the stations information
      operationId: get_stations
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/stations'
        "400":
          description: The stations were not found
          content:
            text/html:
              schema:
                $ref: '#/components/schemas/errorMessage'
              example: The stations were not found
      x-openapi-router-controller: swagger_server.controllers.raw_data_controller
components:
  schemas:
    station_id:
      type: string
    system_information:
      type: object
      properties:
        name:
          type: string
          description: Name of the company
        operator:
          type: string
          description: Operator of the company
        url:
          type: string
          description: URL to the company homepage
        phone_number:
          type: string
          description: Phone of the company
        email:
          type: string
          description: Email of the company
        timezone:
          type: string
          description: Timezone of the company
        license_url:
          type: string
          description: URL to the company license
        start_date:
          type: string
          description: The creation day of the system
      example:
        timezone: timezone
        name: name
        phone_number: phone_number
        operator: operator
        url: url
        email: email
        license_url: license_url
        start_date: start_date
    stations:
      type: object
      properties:
        stations:
          type: array
          items:
            $ref: '#/components/schemas/station_information'
      example:
        stations:
        - station_id: station_id
          name: name
          lon: lon
          lat: lat
          capacity: capacity
        - station_id: station_id
          name: name
          lon: lon
          lat: lat
          capacity: capacity
    station_information:
      type: object
      properties:
        station_id:
          type: string
          description: ID of the Station
        name:
          type: string
          description: Name of the Station
        lat:
          type: string
          description: Latitude of the Station location
        lon:
          type: string
          description: Longitude of the Station location
        capacity:
          type: string
          description: Number of bikes that can be locked in the station
      example:
        station_id: station_id
        name: name
        lon: lon
        lat: lat
        capacity: capacity
    errorMessage:
      maxLength: 256
      type: string
      description: A text message describing an error
    okMessage:
      type: string
      description: A message that describes an OK response
  parameters:
    station_id:
      name: station_id
      in: path
      description: ID of the station
      required: true
      style: simple
      explode: false
      schema:
        $ref: '#/components/schemas/station_id'

